[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public server.php"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
